{
 "title": "DNSmasq - Query Reporting V2.0",
 "description": "Simple Reporting for dnsmasq log entries in rsyslog postgres DB",
 "tags": [
  "RSyslog",
  "DNSMASq "
 ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "cDNSexclude", "label": "DNS exclude pattern", "query": "${VAR_CDNSEXCLUDE}" },
   {
    "name": "Subnet",
    "query": "SELECT distinct CASE WHEN split_part(message,' ', 5) = '127.0.0.1'then '127.0.0.1' ELSE split_part(split_part(message,' ', 5),'.',1)||'.'||split_part(split_part(message,' ', 5),'.',2)||'.'||split_part(split_part(message,' ', 5),'.',3) END FROM systemevents WHERE $__timeFilter(devicereportedtime) and syslogtag like 'dnsmasq%' and message like ' query%' and lower(split_part(message,' ', 3)) not like '($cDNSexclude)' ORDER BY 1"
   },
   {
    "name": "Client",
    "query": "SELECT distinct coalesce(map.hostname, split_part(message,' ', 5)) FROM systemevents as se left outer join ip2hostname as map on split_part(se.message,' ', 5)=map.ip WHERE $__timeFilter(devicereportedtime) and syslogtag like 'dnsmasq%' and message like ' query%' and lower(split_part(message,' ', 5)) like '%'||[[Subnet]]||'%' and lower(split_part(message,' ', 3)) not like '($cDNSexclude)' ORDER BY 1 asc"
   },
   {
    "name": "DNS",
    "query": "SELECT\n  distinct lower(split_part(message,' ', 3))\nFROM systemevents as se left outer join ip2hostname as map on split_part(se.message,' ', 5)=map.ip\nWHERE    $__timeFilter(devicereportedtime) \nand syslogtag like 'dnsmasq%' \nand  message like ' query%'\nand lower(split_part(message,' ', 5)) like '%'||[[Subnet]]||'%'\nand lower(split_part(message,' ', 3)) not like '($cDNSexclude)'\nand coalesce(map.hostname, split_part(message,' ', 5)) in ($Client)\nORDER BY 1"
   }
  ]
 },
 "panels": [
  {
   "title": "Queries over Time",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  DATE_TRUNC('minute', devicereportedtime) AS \"time\",\n--  lower(split_part(message,' ', 2)) as dnsmasq_type,\n  count(1) as query\nFROM systemevents as se left outer join ip2hostname as map on split_part(se.message,' ', 5)=map.ip\nWHERE\n  $__timeFilter(devicereportedtime)\nand syslogtag like 'dnsmasq%' \nand message like ' query%'\nand lower(split_part(message,' ', 3)) not like '$cDNSexclude'\nand lower(split_part(message,' ', 3)) in ($DNS)\nand coalesce(map.hostname, split_part(message,' ', 5)) in ($Client)\nand lower(split_part(message,' ', 5)) like '%'||[[Subnet]]||'%'\nand lower(split_part(message,' ', 3)) not in (\n    SELECT distinct\n      lower(split_part(message,' ', 3)) as dns_query\n    FROM systemevents\n    WHERE\n      $__timeFilter(devicereportedtime)\n    and syslogtag like 'dnsmasq%' \n    and message like ' config%'\n    and lower(split_part(message,' ', 5)) = '0.0.0.0'\n)\ngroup by DATE_TRUNC('minute', devicereportedtime)\n--, lower(split_part(message,' ', 2))\nORDER BY 1"
    },
    {
     "rawSql": "SELECT\n  DATE_TRUNC('minute', devicereportedtime) AS \"time\",\n--  lower(split_part(message,' ', 2)) as dnsmasq_type,\n  count(1) as blocked\nFROM systemevents as se left outer join ip2hostname as map on split_part(se.message,' ', 5)=map.ip\nWHERE\n  $__timeFilter(devicereportedtime)\nand syslogtag like 'dnsmasq%' \nand message like ' query%'\nand lower(split_part(message,' ', 3)) not like '$cDNSexclude'\nand lower(split_part(message,' ', 3)) in ($DNS)\nand coalesce(map.hostname, split_part(message,' ', 5)) in ($Client)\nand lower(split_part(message,' ', 5)) like '%'||[[Subnet]]||'%'\nand lower(split_part(message,' ', 3)) in (\nSELECT distinct\n  lower(split_part(message,' ', 3)) as DNS\nFROM systemevents\nWHERE\n  $__timeFilter(devicereportedtime)\nand syslogtag like 'dnsmasq%' \nand message like ' config%'\nand lower(split_part(message,' ', 5)) = '0.0.0.0'\n)\ngroup by DATE_TRUNC('minute', devicereportedtime)\n--, lower(split_part(message,' ', 3))\nORDER BY 1"
    }
   ]
  },
  { "title": "Processed", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Client",
   "type": "bargauge",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n--  DATE_TRUNC('minute', devicereportedtime) AS \"time\",\n  coalesce(map.hostname, split_part(message,' ', 5)) as client,\n  count(1) as query\nFROM systemevents as se left outer join ip2hostname as map on split_part(se.message,' ', 5)=map.ip\nWHERE\n  $__timeFilter(devicereportedtime)\nand syslogtag like 'dnsmasq%' \nand message like ' query%'\nand lower(split_part(message,' ', 3)) not like '$cDNSexclude'\nand lower(split_part(message,' ', 3)) in ($DNS)\nand lower(split_part(message,' ', 5)) like '%'||[[Subnet]]||'%'\nand lower(split_part(message,' ', 3)) not in (\n    SELECT distinct\n      lower(split_part(message,' ', 3)) as dns_query\n    FROM systemevents\n    WHERE\n      $__timeFilter(devicereportedtime)\n    and syslogtag like 'dnsmasq%' \n    and message like ' config%'\n    and lower(split_part(message,' ', 5)) = '0.0.0.0'\n)\nand coalesce(map.hostname, split_part(message,' ', 5)) in ($Client)\ngroup by\n-- DATE_TRUNC('minute', devicereportedtime), \ncoalesce(map.hostname, split_part(message,' ', 5))\nORDER BY count(1) desc"
    }
   ]
  },
  {
   "title": "DNS",
   "type": "bargauge",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  lower(split_part(message,' ', 3)) as dns_query,\n  count(1) as counter\nFROM systemevents as se left outer join ip2hostname as map on split_part(se.message,' ', 5)=map.ip\nWHERE\n  $__timeFilter(devicereportedtime)\nand syslogtag like 'dnsmasq%' \nand message like ' query%'\nand lower(split_part(message,' ', 3)) not like '$cDNSexclude'\nand lower(split_part(message,' ', 3)) in ($DNS)\nand lower(split_part(message,' ', 5)) like '%'||[[Subnet]]||'%'\nand lower(split_part(message,' ', 3)) not in (\n    SELECT distinct\n      lower(split_part(message,' ', 3)) as dns_query\n    FROM systemevents\n    WHERE\n      $__timeFilter(devicereportedtime)\n    and syslogtag like 'dnsmasq%' \n    and message like ' config%'\n    and lower(split_part(message,' ', 5)) = '0.0.0.0'\n)\nand coalesce(map.hostname, split_part(message,' ', 5)) in ($Client)\ngroup by lower(split_part(message,' ', 3))\nORDER BY 2 desc"
    }
   ]
  },
  { "title": "Blocked", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "Client ",
   "type": "bargauge",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  coalesce(map.hostname, split_part(message,' ', 5)) as client,\n  count(1) as query\nFROM systemevents as se left outer join ip2hostname as map on split_part(se.message,' ', 5)=map.ip\nWHERE\n  $__timeFilter(devicereportedtime)\nand syslogtag like 'dnsmasq%' \nand message like ' query%'\nand lower(split_part(message,' ', 3)) not like '$cDNSexclude'\nand lower(split_part(message,' ', 3)) in ($DNS)\nand lower(split_part(message,' ', 5)) like '%'||[[Subnet]]||'%'\nand coalesce(map.hostname, split_part(message,' ', 5)) in ($Client)\nand lower(split_part(message,' ', 3)) in (\nSELECT distinct\n  lower(split_part(message,' ', 3)) as DNS\nFROM systemevents\nWHERE\n  $__timeFilter(devicereportedtime)\nand syslogtag like 'dnsmasq%' \nand message like ' config%'\nand lower(split_part(message,' ', 5)) = '0.0.0.0'\n)\ngroup by coalesce(map.hostname, split_part(message,' ', 5))\nORDER BY count(1) desc"
    }
   ]
  },
  {
   "title": "DNS",
   "type": "bargauge",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  lower(split_part(message,' ', 3)) as dns_query,\n  count(1) \nFROM systemevents as se left outer join ip2hostname as map on split_part(se.message,' ', 5)=map.ip\nWHERE\n  $__timeFilter(devicereportedtime)\nand syslogtag like 'dnsmasq%' \nand message like ' query%'\nand lower(split_part(message,' ', 3)) not like '$cDNSexclude'\nand lower(split_part(message,' ', 3)) in ($DNS)\nand lower(split_part(message,' ', 5)) like '%'||[[Subnet]]||'%'\nand coalesce(map.hostname, split_part(message,' ', 5)) in ($Client)\nand lower(split_part(message,' ', 3)) in (\nSELECT distinct\n  lower(split_part(message,' ', 3)) as DNS\nFROM systemevents\nWHERE\n  $__timeFilter(devicereportedtime)\nand syslogtag like 'dnsmasq%' \nand message like ' config%'\nand lower(split_part(message,' ', 5)) = '0.0.0.0'\n)\ngroup by lower(split_part(message,' ', 3))\nORDER BY 1"
    }
   ]
  }
 ]
}